mongo:
  host: sym-nexus4-dev-chat-glb-3-ause1-all.symphony.com
  ignoreSSL: false

groupId: testgroup
authentication:
  keystore-file: ${CERTS_DIR}/nexus4/helpdesk.p12
  keystore-password: changeit

helpdesk-bot:
  host: localhost
  port: 8090

helpdesk-service:
  host: localhost
  port: 8081

agent:
  host: nexus4-2.symphony.com
  port: 443

session_auth:
  host: sym-nexus4-dev-chat-glb-3-ause1-all.symphony.com
  port: 8444

key_auth:
  host: sym-nexus4-dev-chat-glb-3-ause1-all.symphony.com
  port: 8444

pod:
  host: nexus4-2.symphony.com
  port: 443

app-authentication:
  api:
    keystore-file: ${CERTS_DIR}/nexus4/helpdesk-app.p12
    keystore-password: changeit