authentication:
  keystore-file: /opt/certificate/cassiano.p12
  keystore-password: changeit

agent:
  host: nexus1-dev.symphony.com

session_auth:
  host: sym-nexus1-dev-chat-glb-2-guse1-all.symphony.com
  port: 8444

key_auth:
  host: sym-nexus1-dev-chat-glb-2-guse1-all.symphony.com
  port: 8444

pod:
  host: nexus1-dev.symphony.com

helpdesk-bot:
  host: localhost.symphony.com
  port: 8090

helpdesk-service:
  host: localhost.symphony.com
  port: 8081

server:
  ssl:
    enabled: true
    key-store: /opt/workspace/HelpDeskBot/helpdesk-bot/src/test/sample/server.keystore
    key-store-password: HQKQvJszAgKtgtRjtsR23KdYstMff6

groupId: cassiano
agentStreamId: GdjwfA0H5UeZ9PLffBtINX___p9nVVKgdA
