authentication:
  keystore-file: ${CERTS_DIR}/helpdesk.p12
  keystore-password: changeit

agent:
  host: nexus2-dev.symphony.com

session_auth:
  host: sym-nexus2-dev-chat-glb-2-guse1-all.symphony.com
  port: 8444

key_auth:
  host: sym-nexus2-dev-chat-glb-2-guse1-all.symphony.com
  port: 8444

pod:
  host: nexus2-dev.symphony.com

memberServiceUrl: http://localhost:8080/helpdesk/service
ticketServiceUrl: http://localhost:8080/helpdesk/service
