mongo:
  host: sym-nexus1-dev-chat-glb-3-ause1-all.symphony.com

groupId: testgroup
authentication:
  keystore-file: ${CERTS_DIR}/helpdesk-nexus1.p12
  keystore-password: changeit

helpdesk-bot:
  host: localhost.symphony.com
  port: 8090

helpdesk-service:
  host: localhost.symphony.com
  port: 8081

agent:
  host: nexus1-2.symphony.com
  port: 443

session_auth:
  host: sym-nexus1-dev-chat-glb-3-ause1-all.symphony.com
  port: 8444

key_auth:
  host: sym-nexus1-dev-chat-glb-3-ause1-all.symphony.com
  port: 8444

pod:
  host: nexus1-2.symphony.com
  port: 443