swagger: '2.0'
info:
  version: '0.0.1'
  title: Help Desk Bot
  description:
produces:
  - application/json
tags:
  - Service
schemes:
  - http
  - https
basePath: '/helpdesk'
paths:
  /v1/ticket/{ticketId}/accept:
    post:
      summary: Notify the help desk bot that a ticket has been accepted by an agent.
      operationId: acceptTicket
      parameters:
        - name: ticketId
          in: path
          required: true
          type: string
        - name: agentId
          in: header
          required: true
          type: integer
          format: int64
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TicketResponse'
        '400':
          description: BAD REQUEST |
            Ticket Id could not be found.
            Agent Id could not be found.
            Required parameter was not provided.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: INTERNAL SERVER ERROR
          schema:
            $ref: '#/definitions/Error'

      tags:
        - Ticket
  /v1/makerchecker/accept:
    post:
      summary: Notify the help desk bot that a message has been accepted for sending by another agent.
      operationId: acceptMakerCheckerMessage
      parameters:
        - name: message
          in: body
          required: true
          schema:
            $ref: '#/definitions/MakerCheckerMessageDetail'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MakerCheckerResponse'
        '400':
          description: BAD REQUEST |
            Invalid stream id.
            Invald group id.
            Invalid proxy to stream id.
            Message Id could not be found at message timestamp.
            Required parameter was not provided.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: INTERNAL SERVER ERROR
          schema:
            $ref: '#/definitions/Error'
      tags:
        - MakerChecker
  /v1/{groupId}/healthcheck:
    get:
      summary: Check the health of a specific help desk bot.
      operationId: healthcheck
      parameters:
        - name: groupId
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/HealthcheckResponse'
        '500':
          description: INTERNAL SERVER ERROR
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Healthcheck
definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  SuccessResponse:
    type: object
    properties:
      message:
        type: string
  TicketResponse:
    type: object
    properties:
      message:
        type: string
      ticketId:
        type: string
      state:
        type: string
        description: |
          Accepted states - UNSERVICED, UNRESOLVED, RESOLVED
      user:
        $ref: '#/definitions/User'
  MakerCheckerResponse:
    type: object
    properties:
      message:
        type: string
      makerCheckerMessageDetail:
        $ref: '#/definitions/MakerCheckerMessageDetail'
      user:
        $ref: '#/definitions/User'
  HealthcheckResponse:
    type: object
    properties:
      podConnectivityCheck:
        type: boolean
      podConnectivityError:
        type: string
      agentConnectivityCheck:
        type: boolean
      agentConnectivityError:
        type: string
  MakerCheckerMessageDetail:
    type: object
    properties:
      type:
        type: string
        required: true
      streamId:
        type: string
        required: true
      proxyToStreamIds:
        type: array
        items:
          type: string
        required: true
      timeStamp:
        type: string
        required: true
      messageId:
        type: string
        required: true
      groupId:
        type: string
        required: true
      userId:
        type: string
        required: true
        description: The userId of the user who accepted the maker checker message.
      attachmentId:
        type: string
        required: false
  User:
    type: object
    properties:
      userId:
        type: integer
        format: int64
      displayName:
        type: string