#This is a sample help desk service externalized config.
helpdesk:
  service:
    databaseDriver: com.mysql.cj.jdbc.Driver
    databaseUrl: jdbc:mysql://localhost:3306/helpdesk
    databaseUser: root
    databasePassword: password
    membershipTableName: memberTable
    ticketTableName: ticketTable
