#This is a sample help desk service externalized config.
helpdesk:
  mongo:
    host: mongo.symphony.com
    port: 27017
    database: helpdesk
    socketTimeout: 10000
    connectTimeout: 5000
    waitTimeout: 10000
    readPreference: nearest
    writeConcern: majority
