#This is a sample help desk service externalized config.
helpdesk:
  service:
    databaseDriver: com.mysql.cj.jdbc.Driver
    databaseUrl: jdbc:mysql://localhost:3306/helpdesk
    databaseUser: root
    databasePassword: password
    membershipTableName: memberTable
    ticketTableName: ticketTable
  mongo:
    host: mongo.symphony.com
    port: 27017
    database: maestro
    socketTimeout: 10000
    connectTimeout: 5000
    waitTimeout: 10000
    readPreference: nearest
    writeConcern: majority
