#This is a sample help desk bot properties config.
server:
  port : 8090

email: helpdesk@symphony.com
groupId: Test

claimMessageTemplate:
  "<div class=\"entity\" data-entity-id=\"helpdesk\">
    <card class=\"barStyle\">
      <header>
        <span>${entity['helpdesk'].message.header}</span>
      </header>
      <body>
        <span>${entity['helpdesk'].message.body}</span>
      </body>
    </card>
  </div>"
claimEntityTemplate:
  "{
      \"helpdesk\": {
        \"type\": \"com.symphony.bots.helpdesk.event.ticket\",
        \"version\": \"1.0\",
        \"url\": \"{HOST}/helpdesk/v1/ticket/{TICKET_ID}/accept\",
        \"ticketId\": \"{TICKET_ID}\",
        \"state\": \"{TICKET_STATE}\",
        \"user\": {
           \"displayName\": \"{USER_NAME}\"
        },
        \"message\" : {
        \"type\": \"com.symphony.bots.helpdesk.event.ticket\",
        \"version\": \"1.0\",
        \"header\": \"{HEADER}\",
        \"body\": \"{BODY}\"
      }
    }
  }"
claimEntityBodyTemplate: Company: {COMPANY}<br/>Customer: {USER_NAME}<br/>Question: {QUESTION}
claimEntityHeaderTemplate: Equites Desk Bot
claimEntityHostTemplate: http://localhost.com:8090

makerCheckerMessageTemplate: This is a maker checker message.
makerCheckerEntityTemplate:
  "makerCheckerObject: {
    type: org.symphonyoss.helpdesk.makerCheckerMessage,version: 1.0,
    uid : \"{UID}\",
    streamId : \"{STREAM_ID}\",
    proxyToStreamId : \"{PROXY_TO_STREAM_ID}\",
    timestamp : \"{TIMESTAMP}\",
    messageId : \"{MESSAGE_ID}\"}"

aiServicePrefix:
aiDefaultPrefix: /
closeTicketCommand: Close Ticket
acceptTicketCommand: Accept Ticket
addMemberCommand: Add Member
acceptTicketAgentSuccessResponse: Ticket claimed successfully.
acceptTicketClientSuccessResponse: You have been connected to an agent.
closeTicketSuccessResponse: Ticket closed successfully.
addMemberAgentSuccessResponse: New member has been added to the help desk.
addMemberClientSuccessResponse: Your membership to the help desk has been updated by an agent.
ticketCreationMessage: Ticket created successfully.