#This is a sample help desk bot properties config.
server:
  address: 0.0.0.0
  port : 8090
  display-name: Help Desk Bot
  context-path: /helpdesk-bot
  connection-timeout: 20000

email: helpdesk@symphony.com

claimEntityHeader: "<b>Equities Desk Bot</b>"

idle-ticket:
  message: "has been idle for 60 minutes."
  timeout: 1
  unit: "HOURS"

instructional-ticket:
  message: " to close the ticket upon ticket resolution."
  command: "<mention uid=\"%s\"/> <b>Close</b>"

aiServicePrefix: "@"
closeTicketCommand: "Close"
createTicketMessage: "Ticket created successfully"
acceptTicketClientSuccessResponse: "You have been connected to an agent."
closeTicketSuccessResponse: "Thank you for contacting us, this session is now over. Any new messages in this chat will be delivered to the JPM Equity Team as a new session."
welcomeMessage: "Thanks for contacting the Equity Team at JPM. All messages sent in this chat will be delivered to the JPM Equity Team."
noAgentsMessage: "There are no available agents to attend your ticket right now. Please wait for a moment while we connect you to a new agent."
serviceRoomWasNotCreated: "There was a problem trying to create the service room. Please try again."

app-authentication:
  enabled: true
  pod:
    host: ${pod.host}
    port: ${pod.port:443}
  session_auth:
    host: ${session_auth.host}
    port: ${session_auth.port:443}
  filter:
    url-patterns:
      - "/v1/*"

http-client:
  connect-timeout: 45000
  read-timeout: 45000

certs:
  dir: '' #should be defined as environment variable CERTS_DIR

provisioning:
  execute: false
  ca:
    generate-keystore: false
    overwrite: false
  service-account:
    generate-keystore: false
    overwrite: false