#This is a sample help desk bot properties config.
server:
  port : 8443
  ssl:
    key-store: /Users/nick.tarsillo/dev/java/symphony/projects/symphony-jpm-helpdesk/helpdesk-bot/src/main/resources/sample/server.keystore
    key-store-password: HQKQvJszAgKtgtRjtsR23KdYstMff6
    trust-store: /Users/nick.tarsillo/dev/java/symphony/projects/symphony-jpm-helpdesk/helpdesk-bot/src/main/resources/sample/server.truststore
    trust-store-password: HQKQvJszAgKtgtRjtsR23KdYstMff6

#This is a sample help desk bot externalized config.
email: bot.user1@symphony.com
sessionAuthUrl: https://develop-api.symphony.com:8444/sessionauth
keyAuthUrl:  https://develop-api.symphony.com:8444/keyauth
agentUrl: https://develop.symphony.com/agent
podUrl: https://develop.symphony.com/pod
keyStoreFile: /Users/nick.tarsillo/dev/java/symphony/projects/symphony-jpm-helpdesk/helpdesk-bot/src/main/resources/sample/bot.user1.p12
keyStorePassword: changeit
trustStoreFile: /Users/nick.tarsillo/dev/java/symphony/projects/symphony-jpm-helpdesk/helpdesk-bot/src/main/resources/sample/auth.truststore
trustStorePassword: changeit

groupId: Test
defaultAgentEmail: nick.tarsillo@symphony.com
agentStreamId: TVuowHrmpEdGeDXM16thIn___qBGsaWUdA

memberServiceUrl: https://localhost.symphony.com:8442/helpdesk/service
ticketServiceUrl: https://localhost.symphony.com:8442/helpdesk/service

claimMessageTemplate:
  "<div class=\"entity\" data-entity-id=\"zapierPostMessage\">
    <card class=\"barStyle\">
      <header>
        <span>${entity['zapierPostMessage'].message.header}</span>
      </header>
      <body>
        <span>${entity['zapierPostMessage'].message.body}</span>
      </body>
    </card>
  </div>"

claimEntityTemplate:
  "{
      \"zapierPostMessage\": {
        \"type\": \"com.symphony.bots.helpdesk.event.ticket\",
        \"version\": \"1.0\",
        \"message\" : {
        \"type\": \"com.symphony.integration.zapier.event.message\",
        \"version\": \"1.0\",
        \"header\": \"Equites Desk Bot\",
        \"body\": \"Company: Redrock<br/>Customer: Alex Jones<br/>Question: Who should I speak to do XY and Z?\"
      }
    }
  }"

makerCheckerMessageTemplate: This is a maker checker message.
makerCheckerEntityTemplate:
  "{\"makerCheckerObject\": {
    \"type\": \"org.symphonyoss.helpdesk.makerCheckerMessage\",
    \"version\": 1.0,
    \"uid\" : \"{UID}\",
    \"streamId\" : \"{STREAM_ID}\",
    \"proxyToStreamId\" : \"{PROXY_TO_STREAM_ID}\",
    \"timestamp\" : \"{TIMESTAMP}\",
    \"messageId\" : \"{MESSAGE_ID}\"}
  }"

ticketCreationMessage: Hello client, a new ticket has been created. Please wait while an agent reviews your request.

aiServicePrefix:
aiDefaultPrefix: /
closeTicketCommand: Close Ticket {Ticket_Id}
acceptTicketCommand: Accept Ticket {Ticket_Id}
addMemberCommand: Add Member {@Mention}
acceptTicketAgentSuccessResponse: Ticket claimed successfully.
acceptTicketClientSuccessResponse: You have been connected to an agent.
closeTicketSuccessResponse: Ticket closed successfully.
addMemberAgentSuccessResponse: New member has been added to the help desk.
addMemberClientSuccessResponse: Your membership to the help desk has been updated by an agent.