#This is a sample help desk bot properties config.
server:
  port: 8443
  ssl:
    key-store: /Users/nick.tarsillo/dev/java/symphony/projects/symphony-jpm-helpdesk/helpdesk-bot/src/test/sample/server.keystore
    key-store-password: HQKQvJszAgKtgtRjtsR23KdYstMff6
    trust-store: /Users/nick.tarsillo/dev/java/symphony/projects/symphony-jpm-helpdesk/helpdesk-bot/src/test/sample/server.truststore
    trust-store-password: HQKQvJszAgKtgtRjtsR23KdYstMff6

authentication:
  keystore-file: /Users/nick.tarsillo/Desktop/certs/helpdesk.demo.p12
  keystore-password: changeit
  truststore-file: /Users/nick.tarsillo/Desktop/certs/server.truststore
  truststore-password: changeit

agent:
  host: nexus2-dev.symphony.com

session_auth:
  host: sym-nexus2-dev-chat-glb-2-guse1-all.symphony.com
  port: 8444

key_auth:
  host: sym-nexus2-dev-chat-glb-2-guse1-all.symphony.com
  port: 8444

pod:
  host: nexus2-dev.symphony.com

helpdesk-bot:
  host: localhost.symphony.com
  port: 8443

helpdesk-service:
  host: localhost.symphony.com
  port: 8445

agentStreamId: nlSxIm6wtGZkA9WQyvt_qn___p_f_H9sdA

email: helpdesk.demo@symphony.com
defaultAgentEmail: nick.tarsillo@symphony.com
groupId: Demo

claimEntityHeader: "<b>Equities Desk Bot</b>"

idle-ticket:
  message: "has been idle for 60 minutes."
  timeout: 1
  unit: "HOURS"

instructional-ticket:
  message: " to close the ticket upon ticket resolution."
  command: "<mention uid=\"%s\"/> Close"

aiServicePrefix: "@"
aiDefaultPrefix: "/"
closeTicketCommand: "Close Ticket"
acceptTicketCommand: "Accept Ticket {Ticket_Id}"
addMemberCommand: "Add Member @{Mention} {Membership_Type}"
acceptTicketClientSuccessResponse: "You have been connected to an agent."
createTicketMessage: "Ticket created successfully."
closeTicketSuccessResponse: "Ticket closed successfully."
addMemberAgentSuccessResponse: "New member has been added to the help desk."
addMemberClientSuccessResponse: "Your membership to the help desk has been updated by an agent."
welcomeMessage: "Thanks for contacting the Equity Team at JPM. All messages sent in this chat will be delivered to the JPM Equity Team."