#This is a sample help desk bot properties config.
server:
  address: 0.0.0.0
  port : 8090
  display-name: Help Desk Bot
  context-path: /helpdesk-bot
  connection-timeout: 20000

email: helpdesk@symphony.com

claimEntityHeader: "<b>Equities Desk Bot</b>"

idle-ticket:
  message: "has been idle for 60 minutes."
  timeout: 1
  unit: "HOURS"

instructional-ticket:
  message: " to close the ticket upon ticket resolution."
  command: "<mention uid=\"%s\"/> Close"

aiServicePrefix: "@"
aiDefaultPrefix: "/"
closeTicketCommand: "Close Ticket"
acceptTicketCommand: "Accept Ticket {Ticket_Id}"
addMemberCommand: "Add Member @{Mention} {Membership_Type}"
acceptTicketClientSuccessResponse: "You have been connected to an agent."
createTicketMessage: "Ticket created successfully."
closeTicketSuccessResponse: "Ticket closed successfully."
addMemberAgentSuccessResponse: "New member has been added to the help desk."
addMemberClientSuccessResponse: "Your membership to the help desk has been updated by an agent."
welcomeMessage: "Thanks for contacting the Equity Team at JPM. All messages sent in this chat will be delivered to the JPM Equity Team."