#This is a sample help desk bot properties config.
server:
  address: 0.0.0.0
  port : 8090
  display-name: Help Desk Bot
  context-path: /helpdesk-bot
  connection-timeout: 20000

email: helpdesk@symphony.com

claimEntityHeader: "<b>Equities Desk Bot</b>"

idle-ticket:
  message: "has been idle for 60 minutes."
  timeout: 1
  unit: "HOURS"

makerCheckerMessageTemplate:
  "<div class=\"entity\" data-entity-id=\"makerchecker\">
    <card class=\"barStyle\">
      <header>
        The above message contains an attachment and has therefore not been sent. Please have a checker approve this message.
      </header>
    </card>
  </div>"
makerCheckerEntityTemplate:
  "{
      \"makerchecker\": {
        \"type\": \"com.symphony.bots.helpdesk.event.makerchecker\",
        \"version\": \"1.0\",
        \"uid\" : \"{UID}\",
        \"streamId\" : \"{STREAM_ID}\",
        \"proxyToStreamIds\" : {PROXY_TO_STREAM_IDS},
        \"timestamp\" : \"{TIMESTAMP}\",
        \"messageId\" : \"{MESSAGE_ID}\",
        \"groupId\" : \"{GROUP_ID}\",
        \"type\" : \"{TYPE}\",
        \"attachmentId\" : \"{ATTACHMENT_ID}\"
      }
  }"

aiServicePrefix: "@"
aiDefaultPrefix: "/"
closeTicketCommand: "Close Ticket"
acceptTicketCommand: "Accept Ticket {Ticket_Id}"
addMemberCommand: "Add Member @{Mention} {Membership_Type}"
acceptTicketAgentSuccessResponse: "Ticket claimed successfully."
acceptTicketClientSuccessResponse: "You have been connected to an agent."
closeTicketSuccessResponse: "Ticket closed successfully."
addMemberAgentSuccessResponse: "New member has been added to the help desk."
addMemberClientSuccessResponse: "Your membership to the help desk has been updated by an agent."