#This is a sample help desk bot properties config.
server:
  port : 8090

email: helpdesk@symphony.com
groupId: Test

claimMessageTemplate:
  "<div class=\"entity\" data-entity-id=\"helpdesk\">
    <card class=\"barStyle\">
      <header>
        <span>${entity['helpdesk'].message.header}</span>
      </header>
      <body>
        <span><b>Company:</b> ${entity['helpdesk'].message.company}</span><br/>
        <span><b>Customer:</b> ${entity['helpdesk'].message.customer}</span><br/>
        <span><b>Question:</b> ${entity['helpdesk'].message.question}</span>
      </body>
    </card>
  </div>"

claimEntityTemplate:
  "{
      \"helpdesk\": {
        \"type\": \"com.symphony.bots.helpdesk.event.ticket\",
        \"version\": \"1.0\",
        \"url\": \"{HOST}/v1/ticket/{TICKET_ID}/accept\",
        \"ticketId\": \"{TICKET_ID}\",
        \"state\": \"{TICKET_STATE}\",
        \"user\": {
           \"displayName\": \"{USER_NAME}\"
        },
        \"message\" : {
        \"type\": \"com.symphony.bots.helpdesk.event.ticket\",
        \"version\": \"1.0\",
        \"header\": \"{HEADER}\",
        \"company\": \"{COMPANY}\",
        \"customer\": \"{USER_NAME}\",
        \"question\": \"{QUESTION}\"
      }
    }
  }"

claimEntityHeader: "Equities Desk Bot"

makerCheckerMessageTemplate:
  "<div class=\"entity\" data-entity-id=\"makerchecker\">
    <card class=\"barStyle\">
      <header>
        The above message contains an attachment and has therefore not been sent. Please have a checker approve this message.
      </header>
    </card>
  </div>"
makerCheckerEntityTemplate:
  "{
      \"makerchecker\": {
        \"type\": \"com.symphony.bots.helpdesk.event.makerchecker\",
        \"version\": \"1.0\",
        \"uid\" : \"{UID}\",
        \"streamId\" : \"{STREAM_ID}\",
        \"proxyToStreamIds\" : \"{PROXY_TO_STREAM_IDS}\",
        \"timestamp\" : \"{TIMESTAMP}\",
        \"messageId\" : \"{MESSAGE_ID}\",
        \"groupId\" : \"{GROUP_ID}\",
        \"type\" : \"{TYPE}\",
        \"attachmentId\" : \"{ATTACHMENT_ID}\"
      }
  }"

aiServicePrefix: "@"
aiDefaultPrefix: "/"
closeTicketCommand: "Close Ticket"
acceptTicketCommand: "Accept Ticket {Ticket_Id}"
addMemberCommand: "Add Member @{Mention} {Membership_Type}"
acceptTicketAgentSuccessResponse: "Ticket claimed successfully."
acceptTicketClientSuccessResponse: "You have been connected to an agent."
closeTicketSuccessResponse: "Ticket closed successfully."
addMemberAgentSuccessResponse: "New member has been added to the help desk."
addMemberClientSuccessResponse: "Your membership to the help desk has been updated by an agent."
ticketCreationMessage: "Ticket created successfully."