server:
  port: 8445
  ssl:
    key-store: /Users/nick.tarsillo/dev/java/symphony/projects/symphony-jpm-helpdesk/helpdesk-bot/src/test/sample/server.keystore
    key-store-password: HQKQvJszAgKtgtRjtsR23KdYstMff6
    trust-store: /Users/nick.tarsillo/dev/java/symphony/projects/symphony-jpm-helpdesk/helpdesk-bot/src/test/sample/server.truststore
    trust-store-password: HQKQvJszAgKtgtRjtsR23KdYstMff6
  display-name: Help Desk Service
  context-path: /helpdesk
  connection-timeout: 20000

helpdesk:
  mongo:
    port: 27017
    host: localhost
    database: maestro
    ignoreSSL: true
    socketTimeout: 10000
    connectTimeout: 5000
    waitTimeout: 10000
    readPreference: nearest
    writeConcern: majority
