kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: helpdesk-mongodb
  namespace: default
  labels:
    run: helpdesk-mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: helpdesk-mongodb
    spec:
      containers:
        - name: helpdesk-mongodb
          image: mongo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
              protocol: TCP
