kind: Service
apiVersion: v1
metadata:
  name: helpdesk-renderer-service
  labels:
    run: helpdesk-renderer
spec:
  selector:
    run: helpdesk-renderer
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
