kind: Service
apiVersion: v1
metadata:
  name: helpdesk-api-service
  labels:
    run: helpdesk-api
spec:
  selector:
    run: helpdesk-api
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
